package com.ssrvpn.android

/**
 * Public domestic-service apps that should use the system network instead of SSRVPN.
 *
 * Keep this list conservative. General-purpose browsers, international apps, VPN clients,
 * Root/Hook/module tooling, and private or uncertain packages must continue through SSRVPN.
 * Package names are explicit so the client never scans or classifies a user's installed apps.
 */
internal object DomesticAppBypassPolicy {
    val packageNames: List<String> = listOf(
        "cmb.pb",
        "cn.cyberIdentity.certification",
        "cn.ninebot.ninebot",
        "cn.wps.moffice_eng",
        "cn.wps.moffice_eng.xiaomi.lite",
        "com.alibaba.aliyun",
        "com.alicom.smartdail",
        "com.autonavi.minimap",
        "com.baidu.netdisk",
        "com.chinamworld.main",
        "com.coolapk.market",
        "com.ct.client",
        "com.dada.mobile.shop.android",
        "com.deepseek.chat",
        "com.dothantech.android.yinlifun",
        "com.duokan.phone.remotecontroller",
        "com.eg.android.AlipayGphone",
        "com.huaxiaozhu.rider",
        "com.icbc",
        "com.jingdong.app.mall",
        "com.larus.nova",
        "com.lemon.lv",
        "com.lucky.luckyclient",
        "com.luna.music",
        "com.max.xiaoheihe",
        "com.mi.car.mobile",
        "com.mi.earphone",
        "com.mi.health",
        "com.mipay.wallet",
        "com.miui.calculator",
        "com.miui.cleanmaster",
        "com.miui.compass",
        "com.miui.findmy",
        "com.miui.gallery",
        "com.miui.mediaeditor",
        "com.miui.newmidrive",
        "com.miui.notes",
        "com.miui.password",
        "com.miui.screenrecorder",
        "com.miui.securitymanager",
        "com.miui.themestore",
        "com.miui.virtualsim",
        "com.miui.voiceassistProxy",
        "com.miui.weather2",
        "com.mt.mtxx.mtxx",
        "com.netease.cloudmusic",
        "com.netease.uuremote",
        "com.pupumall.customer",
        "com.sankuai.meituan",
        "com.sankuai.meituan.takeoutnew",
        "com.sina.weibo",
        "com.smile.gifmaker",
        "com.ss.android.lark",
        "com.ss.android.ugc.aweme",
        "com.ss.android.ugc.livelite",
        "com.taobao.idlefish",
        "com.taobao.taobao",
        "com.tencent.androidqqmail",
        "com.tencent.mm",
        "com.tencent.mobileqq",
        "com.tencent.nrc",
        "com.tencent.wetype",
        "com.tencent.wework",
        "com.tmri.app.main",
        "com.wanbangauto.chargepile",
        "com.xiaomi.mibrain.speech",
        "com.xiaomi.scanner",
        "com.xiaomi.shop",
        "com.xiaomi.smarthome",
        "com.xiaomi.superhexa",
        "com.xiaomi.vipaccount",
        "com.xingin.xhs",
        "com.xunmeng.pinduoduo",
        "me.ele",
        "tv.danmaku.bili"
    )

    fun applyInstalled(tryApply: (String) -> Boolean): List<String> =
        packageNames.filter(tryApply)
}
