version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pub-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "dart"
  - package-ecosystem: "gradle"
    directory: "/SSRVPN_Android/android"
    schedule:
      interval: "weekly"
    groups:
      android-gradle-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "android"
