version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
  - package-ecosystem: "pub"
    directory: "/packages/ssrvpn_shared"
    schedule:
      interval: "weekly"
    groups:
      shared-pub:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "dart"
  - package-ecosystem: "pub"
    directory: "/SSRVPN_Android"
    schedule:
      interval: "weekly"
    groups:
      android-pub:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "android"
  - package-ecosystem: "pub"
    directory: "/SSRVPN_MacOS"
    schedule:
      interval: "weekly"
    groups:
      macos-pub:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "macos"
  - package-ecosystem: "pub"
    directory: "/SSRVPN_Windows"
    schedule:
      interval: "weekly"
    groups:
      windows-pub:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "windows"
