# SSRVPN CET Compatibility Fix
# ================================
#
# Windows 11 25H2 (Build 26200+) enforces CET (Control-flow Enforcement
# Technology / Shadow Stack) hardware protection.  The pre-compiled
# flutter_windows.dll from Flutter 3.38.5 contains machine code that is
# incompatible with CET.
#
# This script registers a per-process CET exemption so SSRVPN can run.
# It must be executed with Administrator privileges.
#
# Usage:
#   (Installer)  powershell -ExecutionPolicy Bypass -File ssrvpn_cet_fix.ps1
#   (Manual)     Right-click ssrvpn_cet_fix.bat → Run as Administrator
#
# ===

param(
    [string]$ExeName = "ssrvpn_windows.exe",
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

# ── Determine target executable name ──
# The Flutter runner is the app EXE, and the launcher renames it to _app.exe.
# CET exemption must target the EXE that actually loads flutter_windows.dll.
# If the app is launched via the CET launcher (ssrvpn_windows_launcher.exe),
# the child is ssrvpn_windows_app.exe.
# For direct-launch / installer-integrated setups, it's ssrvpn_windows.exe.

$targetNames = @($ExeName)
if ($ExeName -eq "ssrvpn_windows.exe") {
    $targetNames += "ssrvpn_windows_app.exe"
}

# ── Uninstall mode ──
if ($Uninstall) {
    foreach ($name in $targetNames) {
        try {
            Set-ProcessMitigation -Name $name -Remove -Disable UserShadowStack -ErrorAction SilentlyContinue
            Write-Host "Removed CET exemption for: $name"
        } catch {
            Write-Host "No exemption to remove for: $name"
        }
    }
    Write-Host "[SSRVPN CET Fix] Exemption removed."
    exit 0
}

# ── Check if running as Administrator ──
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "[SSRVPN CET Fix] ERROR: This script requires Administrator privileges."
    Write-Host "Right-click ssrvpn_cet_fix.bat and select 'Run as Administrator'."
    exit 1
}

# ── Apply CET exemption ──
$allOk = $true
foreach ($name in $targetNames) {
    Write-Host "Registering CET exemption for: $name"
    try {
        Set-ProcessMitigation -Name $name -Disable UserShadowStack -ErrorAction Stop
        Write-Host "  [OK] CET disabled for $name"
    } catch {
        Write-Host "  [WARN] Set-ProcessMitigation failed for $name, trying direct registry..."
        # Fallback: write IFEO registry directly
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\$name"
        try {
            # MitigationOptions binary is machine-generated by Windows.
            # Instead of hand-crafting it, we set DisableUserShadowStack=1
            # in the legacy IFEO subkey that predates the structured format.
            New-Item -Path $regPath -Force -ErrorAction SilentlyContinue | Out-Null
            New-ItemProperty -Path $regPath -Name "DisableUserShadowStack" -Value 1 -PropertyType DWORD -Force -ErrorAction Stop | Out-Null
            Write-Host "  [OK] Direct registry CET exemption for $name"
        } catch {
            Write-Host "  [FAIL] Registry fallback also failed: $_"
            $allOk = $false
        }
    }
}

# ── Verify ──
Write-Host ""
Write-Host "Verification:"
foreach ($name in $targetNames) {
    try {
        $mitigation = Get-ProcessMitigation -Name $name -ErrorAction SilentlyContinue
        if ($mitigation -and $mitigation.UserShadowStack -eq "OFF") {
            Write-Host "  [OK] ${name}: CET = OFF"
        } else {
            Write-Host "  [INFO] ${name}: CET state unknown (will apply on next launch)"
        }
    } catch {
        Write-Host "  [INFO] ${name}: cannot query (exe may not be running)"
    }
}

if ($allOk) {
    Write-Host ""
    Write-Host "[SSRVPN CET Fix] Complete. SSRVPN should now launch normally."
} else {
    Write-Host ""
    Write-Host "[SSRVPN CET Fix] Some steps failed. See above for details."
}

if ($allOk) {
    exit 0
}
exit 1
